export type { ConfirmDialogProps as UIConfirmDialogProps } from '@/ui/dialog/confirmDialog.props'
export { default as UIConfirmDialog } from '@/ui/dialog/ConfirmDialog.vue'
export type { DialogProps as UIDialogProps } from '@/ui/dialog/dialog.props'
export { default as UIDialog } from '@/ui/dialog/Dialog.vue'
export { default as UIDialogBody } from '@/ui/dialog/DialogBody.vue'
export { default as UIDialogContainer } from '@/ui/dialog/DialogContainer.vue'
export { default as UIDialogFooter } from '@/ui/dialog/DialogFooter.vue'
export type { DialogFooterButtonProps as UIDialogFooterButtonProps } from '@/ui/dialog/dialogFooterButton.props'
export { default as UIDialogFooterCancel } from '@/ui/dialog/DialogFooterCancel.vue'
export { default as UIDialogFooterPrimary } from '@/ui/dialog/DialogFooterPrimary.vue'
export { default as UIDialogFooterSecondary } from '@/ui/dialog/DialogFooterSecondary.vue'
export { default as UIDialogFooterSubmit } from '@/ui/dialog/DialogFooterSubmit.vue'
export type { DialogHeaderProps as UIDialogHeaderProps } from '@/ui/dialog/dialogHeader.props'
export { default as UIDialogHeader } from '@/ui/dialog/DialogHeader.vue'
export { useOverlay } from '@/ui/dialog/dialogOverlay.composable'
