import path from 'node:path'

import type {
  Adapter,
  AdapterContext,
  RenderedFile,
} from '../types.js'

const START_MARKER = '<!-- wisemen-skills:start -->'
const END_MARKER = '<!-- wisemen-skills:end -->'

function renderSection(ctx: AdapterContext): string {
  const claudeOut = ctx.config.claude.outDir
  const lines: string[] = []

  lines.push(START_MARKER)
  lines.push('')
  lines.push('## Skills from `@wisemen/*` packages')
  lines.push('')
  lines.push(
    '> Generated by `@wisemen/skills-cli`. This section is regenerated on every `wisemen-skills sync` — do not edit between the markers.',
  )
  lines.push('')

  if (ctx.packages.length === 0) {
    lines.push('_No `@wisemen/*` packages with skills are currently installed._')
    lines.push('')
  }
  for (const pkg of ctx.packages) {
    lines.push(`### ${pkg.name} @ ${pkg.version}`)
    lines.push('')

    for (const skill of pkg.skills) {
      const relative = path.posix.join(claudeOut, pkg.shortName, skill.skillName, 'SKILL.md')
      const description = String(skill.frontmatter.description).split('\n')[0]?.trim() ?? ''

      lines.push(`- **${skill.skillName}** — ${description} ([details](./${relative}))`)
    }

    lines.push('')
  }

  lines.push(END_MARKER)

  return lines.join('\n')
}

function composeContent(existing: string | null, section: string): string {
  if (existing === null || existing.trim() === '') {
    return `# AGENTS.md\n\n${section}\n`
  }
  const startIdx = existing.indexOf(START_MARKER)
  const endIdx = existing.indexOf(END_MARKER)

  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    const before = existing.slice(0, startIdx).replace(/\s*$/, '')
    const after = existing.slice(endIdx + END_MARKER.length).replace(/^\s*/, '')
    const prefix = before.length === 0 ? '' : `${before}\n\n`
    const suffix = after.length === 0 ? '\n' : `\n\n${after}`

    return `${prefix}${section}${suffix}`
  }
  // No markers present — append to end.
  const trimmed = existing.replace(/\s*$/, '')

  return `${trimmed}\n\n${section}\n`
}

export const agentsMdAdapter: Adapter = {
  name: 'agents-md',
  render(ctx: AdapterContext): RenderedFile[] {
    return [
      {
        content: composeContent(null, renderSection(ctx)),
        path: ctx.config.agentsMd.path,
        // The sync step will merge with any existing AGENTS.md content.
      },
    ]
  },
}

export const agentsMdMergeHelpers = {
  composeContent,
  END_MARKER,
  renderSection,
  START_MARKER,
}
