import path from 'node:path'

import type {
  Adapter,
  AdapterContext,
  DiscoveredSkill,
  RenderedFile,
} from '../types.js'

function skillPath(outDir: string, skill: DiscoveredSkill): string {
  return path.posix.join(outDir, skill.packageShortName, skill.skillName, 'SKILL.md')
}

function renderIndex(ctx: AdapterContext): string {
  const lines: string[] = []

  lines.push('# Wisemen-distributed Skills')
  lines.push('')
  lines.push(
    '> This directory is generated by `@wisemen/skills-cli`. Do not edit files by hand — changes will be overwritten on the next `wisemen-skills sync`.',
  )
  lines.push('')
  lines.push('Skills are pulled from the installed versions of `@wisemen/*` packages.')
  lines.push('')

  for (const pkg of ctx.packages) {
    lines.push(`## ${pkg.name} @ ${pkg.version}`)
    lines.push('')

    for (const skill of pkg.skills) {
      const relative = path.posix.join(pkg.shortName, skill.skillName, 'SKILL.md')
      const description = String(skill.frontmatter.description).split('\n')[0]?.trim() ?? ''

      lines.push(`- [\`${skill.skillName}\`](./${relative}) — ${description}`)
    }

    lines.push('')
  }

  return `${lines.join('\n').trimEnd()}\n`
}

export const claudeAdapter: Adapter = {
  name: 'claude',
  render(ctx: AdapterContext): RenderedFile[] {
    const outDir = ctx.config.claude.outDir
    const out: RenderedFile[] = []

    for (const pkg of ctx.packages) {
      for (const skill of pkg.skills) {
        out.push({
          content: skill.raw.endsWith('\n') ? skill.raw : `${skill.raw}\n`,
          path: skillPath(outDir, skill),
        })
      }
    }

    out.push({
      content: renderIndex(ctx),
      path: path.posix.join(outDir, 'INDEX.md'),
    })

    return out
  },
}
