import path from 'node:path'

import type {
  Adapter,
  AdapterContext,
  RenderedFile,
} from '../types.js'

function renderLlmsTxt(ctx: AdapterContext): string {
  const claudeOut = ctx.config.claude.outDir
  const lines: string[] = []

  lines.push('# Wisemen Skills')
  lines.push('')
  lines.push('> AI coding skills pulled from installed `@wisemen/*` packages. Generated by `@wisemen/skills-cli` — do not edit by hand.')
  lines.push('')

  if (ctx.packages.length === 0) {
    lines.push('_No `@wisemen/*` packages with skills are currently installed._')
    lines.push('')

    return `${lines.join('\n').trimEnd()}\n`
  }
  for (const pkg of ctx.packages) {
    lines.push(`## ${pkg.name} @ ${pkg.version}`)
    lines.push('')

    for (const skill of pkg.skills) {
      const relative = path.posix.join(claudeOut, pkg.shortName, skill.skillName, 'SKILL.md')
      const description = String(skill.frontmatter.description).split('\n')[0]?.trim() ?? ''

      lines.push(`- [${skill.skillName}](./${relative}): ${description}`)
    }

    lines.push('')
  }

  return `${lines.join('\n').trimEnd()}\n`
}

export const llmsTxtAdapter: Adapter = {
  name: 'llms-txt',
  render(ctx: AdapterContext): RenderedFile[] {
    return [
      {
        content: renderLlmsTxt(ctx),
        path: ctx.config.llmsTxt.path,
      },
    ]
  },
}
