import { DOWNLOAD_URL_EXPIRES_S, UPLOAD_URL_EXPIRES_S } from '#src/providers/constants.js'

export const AZURE_BLOB_STORAGE_DOWNLOAD_URL_EXPIRES_S = DOWNLOAD_URL_EXPIRES_S
export const AZURE_BLOB_STORAGE_UPLOAD_URL_EXPIRES_S = UPLOAD_URL_EXPIRES_S
