export const DEFAULT_MIN_SEARCH_INPUT_LENGTH = 2
export const DEFAULT_MAX_SUB_ACTIONS = 99
export const DEFAULT_MIN_APPLICABILITY_SCORE = 0.24
export const SECONDARY_SCORE_WEIGHT = 0.85
export const PARENT_ACTION_SCORE_PENALTY = -0.15
export const SCORE_GROUP_PRIORITY_THRESHOLD = 0.05
