import {
  ActivityIcon,
  AlertTriangleIcon,
  BookmarkIcon,
  CalendarIcon,
  CheckCircleIcon,
  CheckSquareIcon,
  ClockIcon,
  ClockRewindIcon,
  Cube01Icon,
  Database01Icon,
  Edit01Icon,
  Flag01Icon,
  HeartIcon,
  Home01Icon,
  Hourglass01Icon,
  InfoSquareIcon,
  LayersTwo01Icon,
  Link04Icon,
  Lock01Icon,
  LockUnlocked01Icon,
  MagicWand01Icon,
  Mail01Icon,
  Mail04Icon,
  MarkerPin01Icon,
  Pin01Icon,
  PlaceholderIcon,
  PlaneIcon,
  RouteIcon,
  Star01Icon,
  Stars01Icon,
  Trash01Icon,
  TrendDown01Icon,
  TrendUp01Icon,
  User01Icon,
  ZapIcon,
} from '@wisemen/vue-core-icons'
import type { Component } from 'vue'

import { CustomViewIcon } from '@/types/customViewIcon.type'

export const CUSTOM_VIEW_ICONS_MAP = new Map<CustomViewIcon, Component>([
  [
    CustomViewIcon.LAYERS,
    LayersTwo01Icon,
  ],
  [
    CustomViewIcon.ACTIVITY,
    ActivityIcon,
  ],
  [
    CustomViewIcon.ALERT_TRIANGLE,
    AlertTriangleIcon,
  ],
  [
    CustomViewIcon.BOOKMARK,
    BookmarkIcon,
  ],
  [
    CustomViewIcon.CALENDAR,
    CalendarIcon,
  ],
  [
    CustomViewIcon.CHECK_CIRCLE,
    CheckCircleIcon,
  ],
  [
    CustomViewIcon.CHECK_SQUARE,
    CheckSquareIcon,
  ],
  [
    CustomViewIcon.CLOCK,
    ClockIcon,
  ],
  [
    CustomViewIcon.CLOCK_REWIND,
    ClockRewindIcon,
  ],
  [
    CustomViewIcon.CUBE,
    Cube01Icon,
  ],
  [
    CustomViewIcon.DATABASE,
    Database01Icon,
  ],
  [
    CustomViewIcon.EDIT,
    Edit01Icon,
  ],
  [
    CustomViewIcon.FLAG,
    Flag01Icon,
  ],
  [
    CustomViewIcon.HEART,
    HeartIcon,
  ],
  [
    CustomViewIcon.HOME,
    Home01Icon,
  ],
  [
    CustomViewIcon.HOURGLASS,
    Hourglass01Icon,
  ],
  [
    CustomViewIcon.INFO_SQUARE,
    InfoSquareIcon,
  ],
  [
    CustomViewIcon.LINK_04,
    Link04Icon,
  ],
  [
    CustomViewIcon.LOCK,
    Lock01Icon,
  ],
  [
    CustomViewIcon.MAGIC_WAND,
    MagicWand01Icon,
  ],
  [
    CustomViewIcon.MAIL_01,
    Mail01Icon,
  ],
  [
    CustomViewIcon.MAIL_04,
    Mail04Icon,
  ],
  [
    CustomViewIcon.MARKER_PIN,
    MarkerPin01Icon,
  ],
  [
    CustomViewIcon.UNLOCK,
    LockUnlocked01Icon,
  ],
  [
    CustomViewIcon.PLANE,
    PlaneIcon,
  ],
  [
    CustomViewIcon.PIN,
    Pin01Icon,
  ],
  [
    CustomViewIcon.PLACEHOLDER,
    PlaceholderIcon,
  ],
  [
    CustomViewIcon.ROUTE,
    RouteIcon,
  ],
  [
    CustomViewIcon.STAR,
    Star01Icon,
  ],
  [
    CustomViewIcon.STARS,
    Stars01Icon,
  ],
  [
    CustomViewIcon.TRASH,
    Trash01Icon,
  ],
  [
    CustomViewIcon.TREND_DOWN,
    TrendDown01Icon,
  ],
  [
    CustomViewIcon.TREND_UP,
    TrendUp01Icon,
  ],
  [
    CustomViewIcon.USER,
    User01Icon,
  ],
  [
    CustomViewIcon.ZAP,
    ZapIcon,
  ],
])

export function getCustomViewIconComponent(key: CustomViewIcon): Component {
  return CUSTOM_VIEW_ICONS_MAP.get(key) ?? LayersTwo01Icon
}
