import {
  ActivityIcon,
  AlertTriangleIcon,
  BookmarkIcon,
  CalendarIcon,
  CheckCircleIcon,
  CheckSquareIcon,
  ClockIcon,
  ClockRewindIcon,
  Cube01Icon,
  Database01Icon,
  Edit01Icon,
  Flag01Icon,
  HeartIcon,
  Home01Icon,
  Hourglass01Icon,
  InfoSquareIcon,
  LayersTwo01Icon,
  Link04Icon,
  Lock01Icon,
  LockUnlocked01Icon,
  MagicWand01Icon,
  Mail01Icon,
  Mail04Icon,
  MarkerPin01Icon,
  Pin01Icon,
  PlaceholderIcon,
  PlaneIcon,
  RouteIcon,
  Star01Icon,
  Stars01Icon,
  Trash01Icon,
  TrendDown01Icon,
  TrendUp01Icon,
  User01Icon,
  ZapIcon,
} from '@wisemen/vue-core-icons'
import type { Component } from 'vue'

import type { CustomViewIcon } from '@/types/customViewIcon.type'
import { CUSTOM_VIEW_ICON } from '@/types/customViewIcon.type'

export const CUSTOM_VIEW_ICONS_MAP = new Map<CustomViewIcon, Component>([
  [
    CUSTOM_VIEW_ICON.LAYERS,
    LayersTwo01Icon,
  ],
  [
    CUSTOM_VIEW_ICON.ACTIVITY,
    ActivityIcon,
  ],
  [
    CUSTOM_VIEW_ICON.ALERT_TRIANGLE,
    AlertTriangleIcon,
  ],
  [
    CUSTOM_VIEW_ICON.BOOKMARK,
    BookmarkIcon,
  ],
  [
    CUSTOM_VIEW_ICON.CALENDAR,
    CalendarIcon,
  ],
  [
    CUSTOM_VIEW_ICON.CHECK_CIRCLE,
    CheckCircleIcon,
  ],
  [
    CUSTOM_VIEW_ICON.CHECK_SQUARE,
    CheckSquareIcon,
  ],
  [
    CUSTOM_VIEW_ICON.CLOCK,
    ClockIcon,
  ],
  [
    CUSTOM_VIEW_ICON.CLOCK_REWIND,
    ClockRewindIcon,
  ],
  [
    CUSTOM_VIEW_ICON.CUBE,
    Cube01Icon,
  ],
  [
    CUSTOM_VIEW_ICON.DATABASE,
    Database01Icon,
  ],
  [
    CUSTOM_VIEW_ICON.EDIT,
    Edit01Icon,
  ],
  [
    CUSTOM_VIEW_ICON.FLAG,
    Flag01Icon,
  ],
  [
    CUSTOM_VIEW_ICON.HEART,
    HeartIcon,
  ],
  [
    CUSTOM_VIEW_ICON.HOME,
    Home01Icon,
  ],
  [
    CUSTOM_VIEW_ICON.HOURGLASS,
    Hourglass01Icon,
  ],
  [
    CUSTOM_VIEW_ICON.INFO_SQUARE,
    InfoSquareIcon,
  ],
  [
    CUSTOM_VIEW_ICON.LINK_04,
    Link04Icon,
  ],
  [
    CUSTOM_VIEW_ICON.LOCK,
    Lock01Icon,
  ],
  [
    CUSTOM_VIEW_ICON.MAGIC_WAND,
    MagicWand01Icon,
  ],
  [
    CUSTOM_VIEW_ICON.MAIL_01,
    Mail01Icon,
  ],
  [
    CUSTOM_VIEW_ICON.MAIL_04,
    Mail04Icon,
  ],
  [
    CUSTOM_VIEW_ICON.MARKER_PIN,
    MarkerPin01Icon,
  ],
  [
    CUSTOM_VIEW_ICON.UNLOCK,
    LockUnlocked01Icon,
  ],
  [
    CUSTOM_VIEW_ICON.PLANE,
    PlaneIcon,
  ],
  [
    CUSTOM_VIEW_ICON.PIN,
    Pin01Icon,
  ],
  [
    CUSTOM_VIEW_ICON.PLACEHOLDER,
    PlaceholderIcon,
  ],
  [
    CUSTOM_VIEW_ICON.ROUTE,
    RouteIcon,
  ],
  [
    CUSTOM_VIEW_ICON.STAR,
    Star01Icon,
  ],
  [
    CUSTOM_VIEW_ICON.STARS,
    Stars01Icon,
  ],
  [
    CUSTOM_VIEW_ICON.TRASH,
    Trash01Icon,
  ],
  [
    CUSTOM_VIEW_ICON.TREND_DOWN,
    TrendDown01Icon,
  ],
  [
    CUSTOM_VIEW_ICON.TREND_UP,
    TrendUp01Icon,
  ],
  [
    CUSTOM_VIEW_ICON.USER,
    User01Icon,
  ],
  [
    CUSTOM_VIEW_ICON.ZAP,
    ZapIcon,
  ],
])

export function getCustomViewIconComponent(key: CustomViewIcon): Component {
  return CUSTOM_VIEW_ICONS_MAP.get(key) ?? LayersTwo01Icon
}
