import type { DialogProps } from '@/components/dialog/dialog.props'

export { useDialog } from '@/components/dialog/dialog.composable'
export type VcDialogProps = Omit<DialogProps, 'classConfig' | 'variant'>
export { createDialogStyle } from '@/components/dialog/dialog.style'
export type { DialogTriggerProps as VcDialogTriggerProps } from '@/components/dialog/dialog.type'
export { default as VcDialog } from '@/components/dialog/Dialog.vue'
export { default as VcDialogContainer } from '@/components/dialog/DialogContainer.vue'
export { default as VcDialogCloseButton } from '@/components/dialog/parts/DialogCloseButton.vue'
export { default as VcDialogContent } from '@/components/dialog/parts/DialogContent.vue'
export { default as VcDialogContentTransition } from '@/components/dialog/parts/DialogContentTransition.vue'
export { default as VcDialogDescription } from '@/components/dialog/parts/DialogDescription.vue'
export { default as VcDialogOverlay } from '@/components/dialog/parts/DialogOverlay.vue'
export { default as VcDialogOverlayTransition } from '@/components/dialog/parts/DialogOverlayTransition.vue'
export { default as VcDialogPortal } from '@/components/dialog/parts/DialogPortal.vue'
export { default as VcDialogRoot } from '@/components/dialog/parts/DialogRoot.vue'
export { default as VcDialogTitle } from '@/components/dialog/parts/DialogTitle.vue'
