export { default as UIDashboardPageCenteredContent } from './centered-content/DashboardPageCenteredContent.vue'
export { default as UIDashboardPageCenteredContentHeader } from './centered-content/DashboardPageCenteredContentHeader.vue'
export { default as UIDashboardPageCenteredContentScrollable } from './centered-content/DashboardPageCenteredContentScrollable.vue'
export { default as UIDashboardPageActions } from './content/DashboardPageActions.vue'
export { default as UIDashboardPageContent } from './content/DashboardPageContent.vue'
export { default as UIDashboardPageLoadingState } from './content/DashboardPageLoadingState.vue'
export * from './dashboardPage.type'
export { default as UIDashboardPage } from './DashboardPage.vue'
export { default as UIDashboardPageContainer } from './DashboardPageContainer.vue'
export { default as UIDashboardPageDetailPaneBody } from './detail-pane/DashboardPageDetailPaneBody.vue'
export { default as UIDashboardPageDetailPaneCloseButton } from './detail-pane/DashboardPageDetailPaneCloseButton.vue'
export { default as UIDashboardPageDetailPaneFooter } from './detail-pane/DashboardPageDetailPaneFooter.vue'
export { default as UIDashboardPageDetailPaneHeader } from './detail-pane/DashboardPageDetailPaneHeader.vue'
export { default as UIDashboardPageDetailPaneTabs } from './detail-pane/DashboardPageDetailPaneTabs.vue'
export { default as UIDashboardPageDetailPaneTabsContent } from './detail-pane/DashboardPageDetailPaneTabsContent.vue'
export { default as UIDashboardPageDetailPaneTabsList } from './detail-pane/DashboardPageDetailPaneTabsList.vue'
export { default as UIDashboardPageDetailPaneToggle } from './detail-pane/DashboardPageDetailPaneToggle.vue'
export * from './detail-pane/detailPane.context'
export * from './detail-pane/detailPane.type'
export type { DetailPaneFooterProps as UIDashboardPageDetailPaneFooterProps } from './detail-pane/detailPaneFooter.props'
export type { DetailPaneHeaderProps as UIDashboardPageDetailPaneHeaderProps } from './detail-pane/detailPaneHeader.props'
export { default as UIDashboardPageHeader } from './header/DashboardPageHeader.vue'
export { default as UIDashboardPageHeaderMasterActionButton } from './header/DashboardPageHeaderMasterActionButton.vue'
export { default as UIPage } from './Page.vue'
