import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  PrimaryGeneratedColumn,
  UpdateDateColumn
} from 'typeorm'
import { PushPlatform } from './push-platform.js'

/**
 * One app installation that can receive push notifications.
 *
 * The installation ID stays fixed, the delivery token may rotate, and the associated user may
 * change independently. `tokenGeneration` changes only when the token changes or a revoked
 * installation is reactivated, which prevents late provider results from invalidating a new token.
 *
 * Uniqueness is scoped to `appScope` (the configured provider app/project). A token is active
 * under at most one installation, enforced by a partial unique index on
 * (`appScope`, `tokenHash`) where `revokedAt IS NULL`.
 */
@Entity('push_installation')
@Index('UQ_push_installation_app_installation', ['appScope', 'installationId'], { unique: true })
@Index(
  'UQ_push_installation_app_token',
  ['appScope', 'tokenHash'],
  { unique: true, where: '"revokedAt" IS NULL' }
)
@Index(
  'IDX_push_installation_user_active',
  ['userUuid'],
  { where: '"revokedAt" IS NULL AND "userUuid" IS NOT NULL' }
)
export class PushInstallation {
  @PrimaryGeneratedColumn('uuid', { name: 'uuid' })
  uuid: string

  @CreateDateColumn({ name: 'createdAt', precision: 3 })
  createdAt: Date

  @UpdateDateColumn({ name: 'updatedAt', precision: 3 })
  updatedAt: Date

  /** Generated by the client and kept for the lifetime of the installation. */
  @Column({ name: 'installationId', type: 'uuid' })
  installationId: string

  /**
   * SHA-256 hash of the installation secret. Hidden from queries unless explicitly selected for
   * a possession check.
   */
  @Column({ name: 'installationSecretHash', type: 'varchar', length: 64, select: false })
  installationSecretHash: string

  @Column({ name: 'userUuid', type: 'uuid', nullable: true })
  userUuid: string | null

  @Column({ name: 'appScope', type: 'varchar' })
  appScope: string

  @Column({ name: 'token', type: 'varchar' })
  token: string

  /** SHA-256 of {@link token}, used for uniqueness and for safe logging. */
  @Column({ name: 'tokenHash', type: 'varchar', length: 64 })
  tokenHash: string

  @Column({
    name: 'platform',
    type: 'enum',
    enum: PushPlatform,
    enumName: 'push_installation_platform_enum'
  })
  platform: PushPlatform

  @Column({ name: 'appVersion', type: 'varchar', nullable: true })
  appVersion: string | null

  @Column({ name: 'tokenGeneration', type: 'int', default: 1 })
  tokenGeneration: number

  @Column({ name: 'lastSeenAt', type: 'timestamp', precision: 3, nullable: true })
  lastSeenAt: Date | null

  @Column({ name: 'revokedAt', type: 'timestamp', precision: 3, nullable: true })
  revokedAt: Date | null

  @Column({ name: 'revokedReason', type: 'varchar', nullable: true })
  revokedReason: string | null
}
