export { useAppearanceSetting } from '@/modules/settings/default-preferences/appearance/config'
export { useFontSizeSetting } from '@/modules/settings/default-preferences/font-size/config'
export { useHighContrastSetting } from '@/modules/settings/default-preferences/high-contrast/config'
export { useKeyboardShortcutHintsSetting } from '@/modules/settings/default-preferences/keyboard-shortcut-hints/config'
export { useLanguageSetting } from '@/modules/settings/default-preferences/language/config'
