export interface DesignSystemComponentConfig {
  category: string
  componentName: string
  description: string
  previewPath: string
  previewSetup?: string
  previewTemplate?: string
  sourceFolder: string
  storyTitle: string
  styleFunctionName?: string
  styleImportPath?: string
  targetFolder: string
  title: string
}

export interface DesignSystemComponentGroup {
  name: string
  components: DesignSystemComponentConfig[]
}

const ACTIONS = 'Actions'
const DATA_DISPLAY = 'Data display'
const FEEDBACK = 'Feedback'
const FORMS_INPUTS = 'Forms and inputs'
const LAYOUT_NAVIGATION = 'Layout and navigation'

export const designSystemComponentGroups: DesignSystemComponentGroup[] = [
  {
    name: ACTIONS,
    components: [
      {
        category: ACTIONS,
        componentName: 'Button',
        description: 'Primary action component with variants, sizes, icons, loading state, and interaction states.',
        previewPath: '@/ui/button/button/stories/ButtonPlayground.vue',
        sourceFolder: 'button/button/Button.vue',
        storyTitle: 'Components/Button',
        styleImportPath: '@/ui/button/button/button.style',
        styleFunctionName: 'createButtonStyle',
        targetFolder: 'button',
        title: 'Button',
      },
      {
        category: ACTIONS,
        componentName: 'IconButton',
        description: 'Compact icon-only action button for toolbars, menus, and dense interfaces.',
        previewPath: '@/ui/button/icon/stories/IconButtonPlayground.vue',
        sourceFolder: 'button/icon/IconButton.vue',
        storyTitle: 'Components/IconButton',
        styleImportPath: '@/ui/button/icon/iconButton.style',
        styleFunctionName: 'createIconButtonStyle',
        targetFolder: 'icon-button',
        title: 'Icon Button',
      },
      {
        category: ACTIONS,
        componentName: 'Link',
        description: 'Link-styled action that supports the design-system button variants for navigation.',
        previewPath: '@/ui/button/link/stories/LinkPlayground.vue',
        sourceFolder: 'button/link/Link.vue',
        storyTitle: 'Components/Link',
        styleImportPath: '@/ui/button/link/link.style',
        styleFunctionName: 'createLinkStyle',
        targetFolder: 'link',
        title: 'Link',
      },
      {
        category: ACTIONS,
        componentName: 'MenuItem',
        description: 'Reusable menu action row for dropdowns, context menus, and command surfaces.',
        previewPath: '@/ui/menu-item/stories/MenuItemPlayground.vue',
        sourceFolder: 'menu-item/MenuItem.vue',
        storyTitle: 'Components/MenuItem',
        styleImportPath: '@/ui/menu-item/menuItem.style',
        styleFunctionName: 'createMenuItemStyle',
        targetFolder: 'menu-item',
        title: 'Menu Item',
      },
      {
        category: ACTIONS,
        componentName: 'DropdownMenu',
        description: 'Triggered menu for grouped actions and secondary command lists.',
        previewPath: '@/ui/dropdown-menu/stories/DropdownMenuPlayground.vue',
        sourceFolder: 'dropdown-menu/DropdownMenu.vue',
        storyTitle: 'Components/DropdownMenu',
        targetFolder: 'dropdown-menu',
        title: 'Dropdown Menu',
      },
      {
        category: ACTIONS,
        componentName: 'ContextMenu',
        description: 'Contextual action menu for right-click or long-press workflows.',
        previewPath: '@/ui/context-menu/stories/ContextMenuPlayground.vue',
        sourceFolder: 'context-menu/ContextMenu.vue',
        storyTitle: 'Components/ContextMenu',
        targetFolder: 'context-menu',
        title: 'Context Menu',
      },
    ],
  },
  {
    name: FORMS_INPUTS,
    components: [
      {
        category: FORMS_INPUTS,
        componentName: 'AddressAutocomplete',
        description: 'Address input with autocomplete suggestions supplied by the configured address adapter.',
        previewPath: '@/ui/address-autocomplete/stories/AddressAutocompletePlayground.vue',
        sourceFolder: 'address-autocomplete/AddressAutocomplete.vue',
        storyTitle: 'Components/AddressAutocomplete',
        targetFolder: 'address-autocomplete',
        title: 'Address Autocomplete',
      },
      {
        category: FORMS_INPUTS,
        componentName: 'Autocomplete',
        description: 'Searchable combobox input for selecting an item from an async or local option set.',
        previewPath: '@/ui/autocomplete/stories/AutocompletePlayground.vue',
        sourceFolder: 'autocomplete/Autocomplete.vue',
        storyTitle: 'Components/Autocomplete',
        styleImportPath: '@/ui/autocomplete/autocomplete.style',
        styleFunctionName: 'createAutocompleteStyle',
        targetFolder: 'autocomplete',
        title: 'Autocomplete',
      },
      {
        category: FORMS_INPUTS,
        componentName: 'Checkbox',
        description: 'Binary selection control with label, hint, invalid, and disabled states.',
        previewPath: '@/ui/checkbox/stories/CheckboxPlayground.vue',
        sourceFolder: 'checkbox/Checkbox.vue',
        storyTitle: 'Components/Checkbox',
        styleImportPath: '@/ui/checkbox/base/baseCheckbox.style',
        styleFunctionName: 'createBaseCheckboxStyle',
        targetFolder: 'checkbox',
        title: 'Checkbox',
      },
      {
        category: FORMS_INPUTS,
        componentName: 'CheckboxGroup',
        description: 'Grouped checkbox selection root for multi-select form fields.',
        previewPath: '@/ui/checkbox-group/CheckboxGroupPlayground.vue',
        previewSetup: "import { ref } from 'vue'\n\nconst modelValue = ref<string[]>([])",
        previewTemplate: '<Preview v-model="modelValue" />',
        sourceFolder: 'checkbox-group/CheckboxGroupRoot.vue',
        storyTitle: 'Components/CheckboxGroup',
        targetFolder: 'checkbox-group',
        title: 'Checkbox Group',
      },
      {
        category: FORMS_INPUTS,
        componentName: 'DateField',
        description: 'Date input field with label, hint, validation, and segmented date editing.',
        previewPath: '@/ui/date-field/stories/DateFieldPlayground.vue',
        sourceFolder: 'date-field/DateField.vue',
        storyTitle: 'Components/DateField',
        styleImportPath: '@/ui/date-field/dateField.style',
        styleFunctionName: 'createDateFieldStyle',
        targetFolder: 'date-field',
        title: 'Date Field',
      },
      {
        category: FORMS_INPUTS,
        componentName: 'DatePicker',
        description: 'Calendar picker for selecting a single date.',
        previewPath: '@/ui/date-picker/stories/DatePickerPlayground.vue',
        sourceFolder: 'date-picker/DatePicker.vue',
        storyTitle: 'Components/DatePicker',
        targetFolder: 'date-picker',
        title: 'Date Picker',
      },
      {
        category: FORMS_INPUTS,
        componentName: 'DateRangeField',
        description: 'Date range input field with start and end date editing.',
        previewPath: '@/ui/date-range-field/stories/DateRangeFieldPlayground.vue',
        sourceFolder: 'date-range-field/DateRangeField.vue',
        storyTitle: 'Components/DateRangeField',
        styleImportPath: '@/ui/date-range-field/dateRangeField.style',
        styleFunctionName: 'createDateRangeFieldStyle',
        targetFolder: 'date-range-field',
        title: 'Date Range Field',
      },
      {
        category: FORMS_INPUTS,
        componentName: 'DateRangePicker',
        description: 'Calendar picker for selecting a date interval.',
        previewPath: '@/ui/date-range-picker/stories/DateRangePickerPlayground.vue',
        sourceFolder: 'date-range-picker/DateRangePicker.vue',
        storyTitle: 'Components/DateRangePicker',
        targetFolder: 'date-range-picker',
        title: 'Date Range Picker',
      },
      {
        category: FORMS_INPUTS,
        componentName: 'NumberField',
        description: 'Numeric input field with formatting, step controls, and validation states.',
        previewPath: '@/ui/number-field/stories/NumberFieldPlayground.vue',
        sourceFolder: 'number-field/NumberField.vue',
        storyTitle: 'Components/NumberField',
        styleImportPath: '@/ui/number-field/numberField.style',
        styleFunctionName: 'createNumberFieldStyle',
        targetFolder: 'number-field',
        title: 'Number Field',
      },
      {
        category: FORMS_INPUTS,
        componentName: 'PhoneNumberField',
        description: 'Phone number input field with country-aware formatting and validation states.',
        previewPath: '@/ui/phone-number-field/stories/PhoneNumberFieldPlayground.vue',
        sourceFolder: 'phone-number-field/PhoneNumberField.vue',
        storyTitle: 'Components/PhoneNumberField',
        styleImportPath: '@/ui/phone-number-field/phoneNumberField.style',
        styleFunctionName: 'createPhoneNumberFieldStyle',
        targetFolder: 'phone-number-field',
        title: 'Phone Number Field',
      },
      {
        category: FORMS_INPUTS,
        componentName: 'RadioGroup',
        description: 'Single-choice group for selecting one value from a short option set.',
        previewPath: '@/ui/radio-group/stories/RadioGroupPlayground.vue',
        sourceFolder: 'radio-group/RadioGroupRoot.vue',
        storyTitle: 'Components/RadioGroup',
        styleImportPath: '@/ui/radio-group/base/baseRadioGroup.style',
        styleFunctionName: 'createBaseRadioGroupStyle',
        targetFolder: 'radio-group',
        title: 'Radio Group',
      },
      {
        category: FORMS_INPUTS,
        componentName: 'Select',
        description: 'Select input for choosing one option from a menu of available values.',
        previewPath: '@/ui/select/stories/SelectPlayground.vue',
        sourceFolder: 'select/Select.vue',
        storyTitle: 'Components/Select',
        targetFolder: 'select',
        title: 'Select',
      },
      {
        category: FORMS_INPUTS,
        componentName: 'Switch',
        description: 'Boolean toggle for enabling or disabling a setting.',
        previewPath: '@/ui/switch/stories/SwitchPlayground.vue',
        sourceFolder: 'switch/Switch.vue',
        storyTitle: 'Components/Switch',
        styleImportPath: '@/ui/switch/switch.style',
        styleFunctionName: 'createSwitchStyle',
        targetFolder: 'switch',
        title: 'Switch',
      },
      {
        category: FORMS_INPUTS,
        componentName: 'TextField',
        description: 'Text input field with label, hint, icon, validation, and disabled states.',
        previewPath: '@/ui/text-field/stories/TextFieldPlayground.vue',
        sourceFolder: 'text-field/TextField.vue',
        storyTitle: 'Components/TextField',
        styleImportPath: '@/ui/text-field/textField.style',
        styleFunctionName: 'createTextFieldStyle',
        targetFolder: 'text-field',
        title: 'Text Field',
      },
      {
        category: FORMS_INPUTS,
        componentName: 'TextareaField',
        description: 'Multiline text input field with form states and validation messaging.',
        previewPath: '@/ui/textarea-field/stories/TextareaFieldPlayground.vue',
        sourceFolder: 'textarea-field/TextareaField.vue',
        storyTitle: 'Components/TextareaField',
        styleImportPath: '@/ui/textarea-field/textareaField.style',
        styleFunctionName: 'createTextareaFieldStyle',
        targetFolder: 'textarea-field',
        title: 'Textarea Field',
      },
      {
        category: FORMS_INPUTS,
        componentName: 'TimeField',
        description: 'Time input field with segmented time editing and validation states.',
        previewPath: '@/ui/time-field/stories/TimeFieldPlayground.vue',
        sourceFolder: 'time-field/TimeField.vue',
        storyTitle: 'Components/TimeField',
        styleImportPath: '@/ui/time-field/timeField.style',
        styleFunctionName: 'createTimeFieldStyle',
        targetFolder: 'time-field',
        title: 'Time Field',
      },
    ],
  },
  {
    name: FEEDBACK,
    components: [
      {
        category: FEEDBACK,
        componentName: 'Dialog',
        description: 'Modal dialog shell for focused tasks, confirmations, and blocking flows.',
        previewPath: '@/ui/dialog/stories/DialogPlayground.vue',
        sourceFolder: 'dialog/Dialog.vue',
        storyTitle: 'Components/Dialog',
        styleImportPath: '@/ui/dialog/dialog.style',
        styleFunctionName: 'createDialogStyle',
        targetFolder: 'dialog',
        title: 'Dialog',
      },
      {
        category: FEEDBACK,
        componentName: 'EmptyState',
        description: 'Empty-state composition for missing data, filtered results, and onboarding moments.',
        previewPath: '@/ui/empty-state/stories/EmptyStatePlayground.vue',
        sourceFolder: 'empty-state/EmptyState.vue',
        storyTitle: 'Components/EmptyState',
        targetFolder: 'empty-state',
        title: 'Empty State',
      },
      {
        category: FEEDBACK,
        componentName: 'Loader',
        description: 'Loading indicator for pending content and asynchronous actions.',
        previewPath: '@/ui/loader/stories/LoaderPlayground.vue',
        sourceFolder: 'loader/Loader.vue',
        storyTitle: 'Components/Loader',
        targetFolder: 'loader',
        title: 'Loader',
      },
      {
        category: FEEDBACK,
        componentName: 'Toast',
        description: 'Toast notification content used with the design-system toast utilities.',
        previewPath: '@/ui/toast/stories/ToastDefaultPlayground.vue',
        sourceFolder: 'toast/Toast.vue',
        storyTitle: 'Components/Toast',
        targetFolder: 'toast',
        title: 'Toast',
      },
      {
        category: FEEDBACK,
        componentName: 'Tooltip',
        description: 'Small contextual disclosure for supplemental UI details.',
        previewPath: '@/ui/tooltip/stories/TooltipPlayground.vue',
        sourceFolder: 'tooltip/Tooltip.vue',
        storyTitle: 'Components/Tooltip',
        styleImportPath: '@/ui/tooltip/tooltip.style',
        styleFunctionName: 'createTooltipStyle',
        targetFolder: 'tooltip',
        title: 'Tooltip',
      },
    ],
  },
  {
    name: DATA_DISPLAY,
    components: [
      {
        category: DATA_DISPLAY,
        componentName: 'Avatar',
        description: 'User avatar display with image, fallback initials, sizes, and status states.',
        previewPath: '@/ui/avatar/avatar/stories/AvatarImagePlayground.vue',
        sourceFolder: 'avatar/avatar/Avatar.vue',
        storyTitle: 'Components/Avatar',
        styleImportPath: '@/ui/avatar/avatar/avatar.style',
        styleFunctionName: 'createAvatarStyle',
        targetFolder: 'avatar',
        title: 'Avatar',
      },
      {
        category: DATA_DISPLAY,
        componentName: 'AvatarGroup',
        description: 'Clustered avatar list for representing grouped people or assignments.',
        previewPath: '@/ui/avatar/avatar-group/stories/AvatarGroupPlayground.vue',
        sourceFolder: 'avatar/avatar-group/AvatarGroup.vue',
        storyTitle: 'Components/Avatar Group',
        styleImportPath: '@/ui/avatar/avatar-group/avatarGroup.style',
        styleFunctionName: 'createAvatarGroupStyle',
        targetFolder: 'avatar-group',
        title: 'Avatar Group',
      },
      {
        category: DATA_DISPLAY,
        componentName: 'AvatarLabel',
        description: 'Avatar paired with primary and supporting text for identity rows.',
        previewPath: '@/ui/avatar/avatar-label/stories/AvatarLabelSizesPlayground.vue',
        sourceFolder: 'avatar/avatar-label/AvatarLabel.vue',
        storyTitle: 'Components/Avatar Label',
        styleImportPath: '@/ui/avatar/avatar-label/avatarLabel.style',
        styleFunctionName: 'createAvatarLabelStyle',
        targetFolder: 'avatar-label',
        title: 'Avatar Label',
      },
      {
        category: DATA_DISPLAY,
        componentName: 'Badge',
        description: 'Compact label for status, category, or count-adjacent metadata.',
        previewPath: '@/ui/badge/stories/BadgePlayground.vue',
        sourceFolder: 'badge/Badge.vue',
        storyTitle: 'Components/Badge',
        styleImportPath: '@/ui/badge/badge.style',
        styleFunctionName: 'badgeVariants',
        targetFolder: 'badge',
        title: 'Badge',
      },
      {
        category: DATA_DISPLAY,
        componentName: 'Breadcrumbs',
        description: 'Breadcrumb navigation trail for showing hierarchy and page location.',
        previewPath: '@/ui/breadcrumbs/stories/BreadcrumbPlayground.vue',
        sourceFolder: 'breadcrumbs/BreadcrumbItems.vue',
        storyTitle: 'Components/Breadcrumbs',
        targetFolder: 'breadcrumbs',
        title: 'Breadcrumbs',
      },
      {
        category: DATA_DISPLAY,
        componentName: 'DetailList',
        description: 'Structured key-value list for compact record details.',
        previewPath: '@/ui/detail-list/stories/DetailListPlayground.vue',
        sourceFolder: 'detail-list/DetailList.vue',
        storyTitle: 'Components/DetailList',
        targetFolder: 'detail-list',
        title: 'Detail List',
      },
      {
        category: DATA_DISPLAY,
        componentName: 'NumberBadge',
        description: 'Numeric badge for counters, notification totals, and compact quantitative labels.',
        previewPath: '@/ui/number-badge/stories/NumberBadgePlayground.vue',
        sourceFolder: 'number-badge/NumberBadge.vue',
        storyTitle: 'Components/NumberBadge',
        styleImportPath: '@/ui/number-badge/numberBadge.style',
        styleFunctionName: 'numberBadgeVariants',
        targetFolder: 'number-badge',
        title: 'Number Badge',
      },
      {
        category: DATA_DISPLAY,
        componentName: 'Separator',
        description: 'Horizontal or vertical divider for separating grouped content.',
        previewPath: '@/ui/separator/stories/SeparatorPlayground.vue',
        sourceFolder: 'separator/Separator.vue',
        storyTitle: 'Components/Separator',
        styleImportPath: '@/ui/separator/separator.style',
        styleFunctionName: 'createSeparatorStyle',
        targetFolder: 'separator',
        title: 'Separator',
      },
      {
        category: DATA_DISPLAY,
        componentName: 'Text',
        description: 'Typography primitive for consistent text scale, color, and semantic rendering.',
        previewPath: '@/ui/text/stories/TextPlayground.vue',
        sourceFolder: 'text/Text.vue',
        storyTitle: 'Components/Text',
        styleImportPath: '@/ui/text/text.style',
        styleFunctionName: 'createTextStyle',
        targetFolder: 'text',
        title: 'Text',
      },
      {
        category: DATA_DISPLAY,
        componentName: 'Timeline',
        description: 'Ordered timeline for activity history and step-by-step event lists.',
        previewPath: '@/ui/timeline/stories/TimelinePlayground.vue',
        sourceFolder: 'timeline/Timeline.vue',
        storyTitle: 'Components/Timeline',
        styleImportPath: '@/ui/timeline/timeline.style',
        styleFunctionName: 'timelineVariants',
        targetFolder: 'timeline',
        title: 'Timeline',
      },
    ],
  },
  {
    name: LAYOUT_NAVIGATION,
    components: [
      {
        category: LAYOUT_NAVIGATION,
        componentName: 'ColumnLayout',
        description: 'Column-based layout primitive for responsive content composition.',
        previewPath: '@/ui/column-layout/stories/ColumnLayoutPlayground.vue',
        sourceFolder: 'column-layout/ColumnLayout.vue',
        storyTitle: 'Components/ColumnLayout',
        targetFolder: 'column-layout',
        title: 'Column Layout',
      },
      {
        category: LAYOUT_NAVIGATION,
        componentName: 'DashboardPage',
        description: 'Dashboard page scaffold for arranging page-level headings, actions, and sections.',
        previewPath: '@/ui/dashboard-page/stories/DashboardPagePlayground.vue',
        sourceFolder: 'dashboard-page/DashboardPage.vue',
        storyTitle: 'Components/Dashboard Page',
        targetFolder: 'dashboard-page',
        title: 'Dashboard Page',
      },
      {
        category: LAYOUT_NAVIGATION,
        componentName: 'RowLayout',
        description: 'Row-based layout primitive for responsive horizontal content composition.',
        previewPath: '@/ui/row-layout/stories/RowLayoutPlayground.vue',
        sourceFolder: 'row-layout/RowLayout.vue',
        storyTitle: 'Components/RowLayout',
        targetFolder: 'row-layout',
        title: 'Row Layout',
      },
      {
        category: LAYOUT_NAVIGATION,
        componentName: 'Sidebar',
        description: 'Application sidebar shell for primary navigation and workspace structure.',
        previewPath: '@/ui/sidebar/stories/playground.vue',
        sourceFolder: 'sidebar/MainSidebar.vue',
        storyTitle: 'Components/Sidebar',
        targetFolder: 'sidebar',
        title: 'Sidebar',
      },
      {
        category: LAYOUT_NAVIGATION,
        componentName: 'Tabs',
        description: 'Tabbed navigation for switching between sibling content sections.',
        previewPath: '@/ui/tabs/stories/TabsPlayground.vue',
        sourceFolder: 'tabs/Tabs.vue',
        storyTitle: 'Components/Tabs',
        styleImportPath: '@/ui/tabs/tabs.style',
        styleFunctionName: 'tabsVariants',
        targetFolder: 'tabs',
        title: 'Tabs',
      },
    ],
  },
]

export const designSystemComponents = designSystemComponentGroups.flatMap((group) => group.components)
