export const CUSTOM_VIEW_ICON = {
  ACTIVITY: 'activity',
  ALERT_TRIANGLE: 'alertTriangle',
  BOOKMARK: 'bookmark',
  CALENDAR: 'calendar',
  CHECK_CIRCLE: 'checkCircle',
  CHECK_SQUARE: 'checkSquare',
  CLOCK: 'clock',
  CLOCK_REWIND: 'clockRewind',
  CUBE: 'cube',
  DATABASE: 'database',
  EDIT: 'edit',
  FLAG: 'flag',
  HEART: 'heart',
  HOME: 'home',
  HOURGLASS: 'hourglass',
  INFO_SQUARE: 'infoSquare',
  LAYERS: 'layers',
  LINK_04: 'link04',
  LOCK: 'lock',
  MAGIC_WAND: 'magicWand',
  MAIL_01: 'mail01',
  MAIL_04: 'mail04',
  MARKER_PIN: 'markerPin',
  PIN: 'pin',
  PLACEHOLDER: 'placeholder',
  PLANE: 'plane',
  ROUTE: 'route',
  STAR: 'star',
  STARS: 'stars',
  TRASH: 'trash',
  TREND_DOWN: 'trendDown',
  TREND_UP: 'trendUp',
  UNLOCK: 'unlock',
  USER: 'user',
  ZAP: 'zap',
} as const

export type CustomViewIcon = (typeof CUSTOM_VIEW_ICON)[keyof typeof CUSTOM_VIEW_ICON]
